from __future__ import annotations

import os
import shutil
import subprocess
import threading
import time
from pathlib import Path
from typing import Optional

from ai_company.core.config import settings
from ai_company.core.exceptions import AICompanyError

SSH_DIR = settings.data_dir / "ssh"

# Simple in-memory clone job tracker
_clone_jobs: dict[str, dict] = {}


def _make_job_id(url: str) -> str:
    import hashlib
    h = hashlib.md5(f"{url}-{time.time()}".encode()).hexdigest()[:12]
    return h


def ensure_ssh_dir() -> Path:
    SSH_DIR.mkdir(parents=True, exist_ok=True)
    return SSH_DIR


def list_ssh_keys() -> list[dict[str, str]]:
    ensure_ssh_dir()
    keys = []
    for pub in sorted(SSH_DIR.glob("*.pub")):
        name = pub.stem
        priv = pub.with_suffix("")
        if priv.exists():
            keys.append({
                "name": name,
                "public_key": pub.read_text(encoding="utf-8").strip(),
            })
    return keys


def generate_ssh_key(name: str, email: str = "ai-company@local") -> dict[str, str]:
    ensure_ssh_dir()
    if not name.replace("_", "").replace("-", "").isalnum():
        raise AICompanyError("Key name must be alphanumeric with _ or - only")

    priv_path = SSH_DIR / name
    pub_path = SSH_DIR / f"{name}.pub"

    if priv_path.exists() or pub_path.exists():
        raise AICompanyError(f"SSH key '{name}' already exists")

    ssh_keygen = shutil.which("ssh-keygen")
    if not ssh_keygen:
        raise AICompanyError("ssh-keygen not found. Please install OpenSSH.")

    result = subprocess.run(
        [
            ssh_keygen,
            "-t", "ed25519",
            "-C", email,
            "-f", str(priv_path),
            "-N", "",
        ],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise AICompanyError(f"ssh-keygen failed: {result.stderr}")

    pub_key = pub_path.read_text(encoding="utf-8").strip()
    return {"name": name, "public_key": pub_key}


def delete_ssh_key(name: str) -> bool:
    ensure_ssh_dir()
    priv_path = SSH_DIR / name
    pub_path = SSH_DIR / f"{name}.pub"
    found = False
    for p in (priv_path, pub_path):
        if p.exists():
            p.unlink()
            found = True
    return found


def sync_keys_to_system_ssh() -> dict:
    """Sync SSH keys from data/ssh to ~/.ssh for system-wide use.

    Also creates/updates ~/.ssh/config to ensure git can find and use these keys.
    """
    ensure_ssh_dir()
    system_ssh_dir = Path.home() / ".ssh"
    system_ssh_dir.mkdir(parents=True, exist_ok=True)

    synced = []
    skipped = []
    errors = []
    config_entries = []

    # Read existing config if present
    config_file = system_ssh_dir / "config"
    existing_config = ""
    if config_file.exists():
        existing_config = config_file.read_text(encoding="utf-8")
        # Remove old AI Company managed section
        import re
        existing_config = re.sub(
            r'\n?# >>> AI Company managed keys.*?# <<< AI Company managed keys\n?',
            '',
            existing_config,
            flags=re.DOTALL
        )

    for pub_file in SSH_DIR.glob("*.pub"):
        name = pub_file.stem
        priv_file = pub_file.with_suffix("")

        if not priv_file.exists():
            skipped.append(f"{name} (missing private key)")
            continue

        # Target paths in ~/.ssh - use standard names for common keys
        # All keys go to ~/.ssh/ with their original names
        system_priv = system_ssh_dir / name
        system_pub = system_ssh_dir / f"{name}.pub"

        try:
            import shutil
            shutil.copy2(priv_file, system_priv)
            shutil.copy2(pub_file, system_pub)

            # Set correct permissions (600 for private, 644 for public)
            system_priv.chmod(0o600)
            system_pub.chmod(0o644)

            synced.append(name)
        except Exception as e:
            errors.append(f"{name}: {str(e)}")

    # Build SSH config with all keys
    config_section = "# >>> AI Company managed keys\n# This section is auto-generated by AI Company\n"
    config_section += "Host *\n"
    # Add all synced keys to config
    for key_name in synced:
        if key_name != 'ssh_config':
            config_section += f"    IdentityFile ~/.ssh/{key_name}\n"
    config_section += "    IdentitiesOnly yes\n"
    config_section += "    StrictHostKeyChecking accept-new\n"
    config_section += "# <<< AI Company managed keys\n"

    # Write updated config
    try:
        new_config = config_section + (f"\n{existing_config}" if existing_config else "")
        config_file.write_text(new_config, encoding="utf-8")
        config_file.chmod(0o600)
        synced.append("ssh_config")
    except Exception as e:
        errors.append(f"ssh_config: {str(e)}")

    return {
        "synced": synced,
        "skipped": skipped,
        "errors": errors,
        "system_ssh_dir": str(system_ssh_dir),
        "ai_company_ssh_dir": str(SSH_DIR),
    }


def get_ssh_env() -> dict[str, str]:
    env = os.environ.copy()
    ensure_ssh_dir()

    # Build SSH command with all available private keys
    ssh_keygen = shutil.which("ssh")
    if not ssh_keygen:
        ssh_keygen = "ssh"

    # Find all private keys (files without .pub extension)
    key_files = []
    for f in SSH_DIR.iterdir():
        if f.is_file() and not f.name.endswith('.pub') and not f.name.startswith('.'):
            # Check if corresponding .pub exists (indicates it's a key pair)
            if f.with_suffix('.pub').exists() or f.name in ['id_rsa', 'id_ed25519', 'id_ecdsa', 'id_dsa']:
                key_files.append(f)

    # Build SSH command
    ssh_cmd_parts = [ssh_keygen, "-o", "IdentitiesOnly=yes", "-o", "StrictHostKeyChecking=accept-new", "-F", "/dev/null"]

    # Add all private keys
    for key_file in key_files:
        ssh_cmd_parts.extend(["-i", str(key_file)])

    env["GIT_SSH_COMMAND"] = " ".join(ssh_cmd_parts)

    # Also set SSH_AUTH_SOCK if available (for ssh-agent)
    if "SSH_AUTH_SOCK" in os.environ:
        env["SSH_AUTH_SOCK"] = os.environ["SSH_AUTH_SOCK"]

    return env


def _do_clone(job_id: str, url: str, target_path: str, ssh_key_name: Optional[str], branch: Optional[str]) -> None:
    cwd = Path(target_path).parent
    name = Path(target_path).name
    cwd.mkdir(parents=True, exist_ok=True)

    git = shutil.which("git")
    if not git:
        _clone_jobs[job_id]["status"] = "failed"
        _clone_jobs[job_id]["error"] = "git not found"
        return

    # If SSH key is selected but URL is HTTPS, auto-convert to SSH for compatibility
    clone_url = url
    if ssh_key_name and url.startswith("https://github.com/"):
        suffix = url[len("https://github.com/"):]
        if not suffix.endswith(".git"):
            suffix += ".git"
        clone_url = f"git@github.com:{suffix}"
    elif ssh_key_name and url.startswith("https://"):
        # Warn fallback: we can't auto-convert arbitrary hosts easily
        pass

    env = os.environ.copy()
    ensure_ssh_dir()
    if ssh_key_name:
        key_path = SSH_DIR / ssh_key_name
        if key_path.exists():
            env["GIT_SSH_COMMAND"] = (
                f"ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new -F /dev/null -i {key_path}"
            )
    else:
        env["GIT_SSH_COMMAND"] = (
            f"ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new -F /dev/null"
        )

    cmd = [git, "clone", "--depth", "1", clone_url, str(name)]
    if branch:
        cmd.extend(["--branch", branch])

    process = subprocess.Popen(
        cmd,
        cwd=str(cwd),
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    stdout, stderr = process.communicate()

    job = _clone_jobs.get(job_id)
    if not job:
        return
    if process.returncode != 0:
        job["status"] = "failed"
        job["error"] = stderr or stdout or "git clone failed"
    else:
        job["status"] = "success"
        job["stdout"] = stdout
        job["stderr"] = stderr


def start_clone(
    url: str,
    target_path: str,
    ssh_key_name: Optional[str] = None,
    branch: Optional[str] = None,
) -> str:
    job_id = _make_job_id(url)
    _clone_jobs[job_id] = {
        "id": job_id,
        "url": url,
        "target_path": target_path,
        "status": "running",
        "created_at": time.time(),
    }
    t = threading.Thread(
        target=_do_clone,
        args=(job_id, url, target_path, ssh_key_name, branch),
        daemon=True,
    )
    t.start()
    return job_id


def get_clone_status(job_id: str) -> dict | None:
    return _clone_jobs.get(job_id)


def clone_repository(
    url: str,
    target_path: str,
    ssh_key_name: Optional[str] = None,
    branch: Optional[str] = None,
) -> dict[str, str]:
    job_id = start_clone(url, target_path, ssh_key_name, branch)
    # Wait up to 60 seconds for quick clones
    for _ in range(60):
        time.sleep(1)
        job = get_clone_status(job_id)
        if not job or job["status"] != "running":
            break
    job = get_clone_status(job_id)
    if not job:
        return {"path": str(target_path), "status": "unknown"}
    if job["status"] == "failed":
        raise AICompanyError(job.get("error", "git clone failed"))
    return {"path": str(target_path), "status": job["status"], "stdout": job.get("stdout", ""), "stderr": job.get("stderr", "")}
